//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("More.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feet.
        /// </summary>
        internal static string FootUnits {
            get {
                return ResourceManager.GetString("FootUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiB.
        /// </summary>
        internal static string GibibyteUnits {
            get {
                return ResourceManager.GetString("GibibyteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string GigabyteUnits {
            get {
                return ResourceManager.GetString("GigabyteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHz.
        /// </summary>
        internal static string GigahertzUnits {
            get {
                return ResourceManager.GetString("GigahertzUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hz.
        /// </summary>
        internal static string HertzUnits {
            get {
                return ResourceManager.GetString("HertzUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiB.
        /// </summary>
        internal static string KibibyteUnits {
            get {
                return ResourceManager.GetString("KibibyteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string KilobyteUnits {
            get {
                return ResourceManager.GetString("KilobyteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kHz.
        /// </summary>
        internal static string KilohertzUnits {
            get {
                return ResourceManager.GetString("KilohertzUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string KilometerUnits {
            get {
                return ResourceManager.GetString("KilometerUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        internal static string MebibyteUnits {
            get {
                return ResourceManager.GetString("MebibyteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MegabyteUnits {
            get {
                return ResourceManager.GetString("MegabyteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHz.
        /// </summary>
        internal static string MegahertzUnits {
            get {
                return ResourceManager.GetString("MegahertzUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string MeterUnits {
            get {
                return ResourceManager.GetString("MeterUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles.
        /// </summary>
        internal static string MileUnits {
            get {
                return ResourceManager.GetString("MileUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric value is required..
        /// </summary>
        internal static string NumericValueRequired {
            get {
                return ResourceManager.GetString("NumericValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiB.
        /// </summary>
        internal static string TebibyteUnits {
            get {
                return ResourceManager.GetString("TebibyteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string TerabyteUnits {
            get {
                return ResourceManager.GetString("TerabyteUnits", resourceCulture);
            }
        }
    }
}
